-- COMENTARIO DE UMA LINHA
/* COMENTAR
    MAIS DE 
    UMA LINHA*/
  
-- ESTRURA DO COMANDO DML SELECT  
    
SELECT  -- AS COLUNAS A SEREM PROJETADAS, SEPARADAS POR VÍRGULA
    *   -- PARA PROJETAR TODAS AS COLUNAS DA ORIGEM (FROM) UTILIZAR O *
FROM    -- TRAZER A ORIGEM DE ONDE SERAO EXTRAÍDOS OS DADOS
        -- PODEM SER TABELAS, VIEWS, SUBQUERIES
        
WHERE   -- PARA A RESTRIÇÃO DE LINHAS, MOSTRAR LINHAS QUE ATENDEM 
        -- UMA CONDIÇÃO (UTILIZAR OS OPERADORES RELACIONAIS : =, >=, <=, <>, !=)
        -- OPERADORES LÓGICOS : NOT, AND, OR
        -- OUTROS OPERADORES : BETWEEN, LIKE
        
GROUP BY -- ORGANIZAR O RESULTADO COM SUB GRUPOS

HAVING -- PARA RESTRIÇÃO DE SUBGRUPOS (MESMO OPERADORES DE WHERE)
    
ORDER BY -- UTILIZADA PARA ORDENAR O RESULTADO